class Solution {
public:
    vector<int> twoSum(vector<int>& numbers, int target) {
        //we need to focus on one indexed array of integers i.e. the array starts from one not zero ..
        //as the array  is already sorted then we are free to use two pointer approach here...
        int n=numbers.size();
        int i=0,j=numbers.size()-1;
        while(i<j){ //to avoid the case where somehow i and j pointing to same element...
            int sum=numbers[i]+numbers[j];
            if(sum>target) j--; // if the sum is greater than target then we will decrement j to lower value of sum..
            else if(sum<target) i++; //if the sum is less than target then we will increment i to make higher value of sum...
            //if else condition satisfies then we will return one based indices ...
            else return {i+1,j+1}; //if sum is equal to target then we will return i and j as the indices of those two numbers...
        }
        return {};// if we reach here that means even after all iterations we are not able to find any two number such that its sum is equal to its target so we can directly  return an empty  vector here...
    }
};