class Solution {
public:
    int maxArea(vector<int>& height) {
        // here as optimization we can apply two pointer approach here for finding the maximum area of the water that can be stored in the container...
        int maxarea=0; // in this variable we will be storing our final result and also this will be used to compare with current area if that is greater then we will store it in this..
        int i=0,j=height.size()-1; //two pointers from start and end they will check heights 
        while(i<j){ // as a container needs atleast two walls to store some water so both should not coincide in any case like pointing to single wall only as that is not valid here so we exclude equality here...
            int min_height=min(height[i],height[j]); //as the height and hence area will depend on the minimum height as the height of water stored will be equal to minimum of both heights irrespective of the greater height...
            int width=j-i; //width will hence be equal to the distance between both walls which will be found be i and j..
            maxarea=max(maxarea,min_height*width); //storing max of both areas...
            if(height[i]<height[j])i++; //if height at ith is smaller than j we will move i forward to find greater wall if any exists...
            else j--; //else j will be smaller height so we will decrement j in order to find gerater height if it exists..
        }
        return maxarea; //finally we found our maxarea and hence we can return it as our answer...
    }
};