class Solution {
public:
    vector<int> shuffle(vector<int>& nums, int n) {
        int size=nums.size(); //to store the size of the given vector 

        vector<int> result(size); //this vector will store the required output and will be returned at output..

        int st=0; //this is like a pointer that points to starting element of the vector ...
        int mid=n; //this is like a pointer that points to the middle element of the vector
        
        int i=0; //this is the iterator that  will iterator through whole vector in result...

        while(st<mid&&mid<size){ // here st should be always less than mid and mid should be less than size of nums to make sure the logic is correct...

            result[i++]=nums[st++];//here the element at st position in nums will be stored at ith  index in result and after that i and st will be updated as incremented by one...
            //here i will be used  as suppose 1 and updated as 2
            result[i++]=nums[mid++]; //now at the ith position which was updated from above line will store here the element at mid position in nums and after this i and mid will be incremented by one and get updated...
            //here i will be used as 2 suppose and updated as 3...

            //similarly  after using st and mid in these lines they will be automatically updated...
        }

        return result; //returning the final output stored in this vector...
    }
};