class Solution {
public:
    int removeDuplicates(vector<int>& nums) {
        //here the main key point is that the array  is sorted so we can use two pointers here for dealing with our problem....
        //here we will assign the unique values after k++ and then after it from 0 to k we will get the sorted array  with unique elements in sorted order...
        int k=0; //initialize k with zero and at the end this value will be returned at end as it keeps tracks of the last unique element...
        for(int i=0;i<nums.size();i++){ // will iterate over each element so k and i are two pointers here..
            if(nums[k]!=nums[i]){
                //if the elements at kth index and  ith  index are not equal...
                k++; // increment the  k first and then assign that unique value  at kth index...
                nums[k]=nums[i];
            }
            //if the above condition is not satisfied then it means that the elements are equal and we will simply move forward as we want unique elements only...
        }
        return k+1; // as k is the index and k is actually the number of unique elements so we will return incremented by one value of k...
    }
};