class Solution {
public:
    int reverse(int x) {
        int result=0;
        while(x!=0){
            int remainder=x%10;//extracting the last digit...
            if(result>INT_MAX/10 or (result==INT_MAX/10 and remainder>7)) return 0; //this handles positive overflow... 
            if(result<INT_MIN/10 or (result==INT_MIN/10 and remainder<-8)) return  0;//his handles negative overflow...

            //this is the else part...
            result=(result*10)+remainder;//adding it in a variable...
            x=x/10;  //updating x for removing the last digit...
        }
        return result; //finally  returning the output..
    }
};
