class Solution {
public:
    vector<int> findErrorNums(vector<int>& nums) {
        // we may intialize the two variables with -1 if something not found then instead of getting garbage value we can directly  return {-1,-1} indicating nothing found to make our code robust...
        int duplicate=-1;
        int missing=-1;

        //here the special case is like the every number can be equal to its index...
        // this vector has the size equals to the size of nums +1 because we want from 1 t0 n and without adding one it will not be upto last element...
        vector<int> count(nums.size()+1,0); //this counts the number of occurances of each element in the given vector...
        for(int x: nums){ //range based loop here to iterate each element by its value not by its index...
            count[x]++; //if any value is repeated then at same index u can say the value will be 2 and missing value will become automatically 0...

        }

        for(int i=1;i<=nums.size();i++){ //incex based loop here it is started from one because the 0th element is not in use becase the element started from one...
        if(count[i]==2) duplicate=i;
        if(count[i]==0) missing=i; //as the values are equal to their indices so we dont need to access the element at that index...

        }
        return {duplicate,missing};//after that we will return duplicate and missing in a vector...

    }

};